#!/usr/bin/env sh

commit_msg=$(cat "$1")

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert): .+$'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo ""
    echo "❌ Invalid commit message."
    echo ""
    echo "Commit message must follow the Conventional Commits format:"
    echo ""
    echo "  <type>: <description>"
    echo ""
    echo "Allowed types:"
    echo "  feat | fix | docs | style | refactor | perf | test | build | ci | chore | revert"
    echo ""
    echo "Examples:"
    echo "  feat: desc"
    echo ""
    exit 1
fi